// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chzmlasxdyawxktzytvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoem1sYXN4ZHlhd3hrdHp5dHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjgwNTAsImV4cCI6MjA1NzQ0NDA1MH0.dI0xnSkvkHew9bSbI6wkysHpyIoYQCH4o0X0KbeuIYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);